{% set name = "multimethod" %}
{% set version = "1.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2bfd270a30ee4b56e64b94b8353ed10f7e7aa769cedf6cb8f1d429ce50d72ea

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - multimethod

about:
  home: https://github.com/coady/multimethod
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Multiple argument dispatching.
  doc_url: https://coady.github.io/multimethod/

extra:
  recipe-maintainers:
    - albop
