{% set name = "multimethod" %}
{% set version = "1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef40713d84da4015285122a16f57bf5066cc7876b5eaf183262f3c34668c6ad3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

test:
  imports:
    - multimethod

about:
  home: https://github.com/coady/multimethod
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Multiple argument dispatching.
  doc_url: https://coady.github.io/multimethod/

extra:
  recipe-maintainers:
    - timkpaine
    - albop
